services:
  nginx:
    image: nginx:latest
    container_name: pdf_nginx
    ports:
      - "8000:80"
      - "4433:443" # Enable this if you're using HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/myconf.conf:ro
      - ./pdf_files:/usr/share/nginx/html

