version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: pdf_nginx
    ports:
      - "80:80"
      - "443:443" # Enable this if you're using HTTPS
    volumes:
      # Mount the custom nginx.conf file
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the PDF files directory as the document root
      - ./pdf_files:/var/www/yourdomain:ro
    networks:
      - pdf_network

networks:
  pdf_network:
    driver: bridge

